model = "gpt-5-codex"
model_reasoning_effort = "medium"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "YOUR_API_KEY"]

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_MCP_PAT"

[mcp_servers.gitkraken]
command = "gk"
args = ["mcp"]

[projects."/workspaces/pihole-dnspropagate"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
