name: Manual Image Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to publish (e.g., 1.0.0-rc.1 or dev)'
        required: true
      platforms:
        description: 'Target platforms (comma-separated)'
        default: linux/amd64
        required: false

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/thomaslazar/pihole-dnspropagate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ github.event.inputs.platforms || 'linux/amd64' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}

      - name: Output digest
        run: |
          echo "Published ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}"
